version: "3.0"
services:
#  web:
#    container_name: "web"
#    image: nginx:alpine
#    depends_on:
#      - app
#    ports:
#      - "80:80"
#    volumes:
#      - ./src/conf.d:/etc/nginx/conf.d
#    networks:
#      - custom2
  db:
    container_name: "rabbit_mg_DB"
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "9001:5432"
    networks:
      - custom2
  app:
    build:
      context: .
#    image: softikdimon/web_gymkhana_bot_server-app:${TAG}
    container_name: "fastapi_app"
    command: ["/app/app.sh"]
    ports:
      - "9000:8000"
    depends_on:
      - db
    networks:
      - custom2

networks:
  custom2:
    driver: bridge




