version: "3.0"
services:
  db_dev:
    container_name: "rabbit_mg_Postgres"
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myuniquepassword
      - POSTGRES_DB=postgres
    ports:
      - "9001:5432"
    networks:
      - custom2
  app:
    image: "softikdimon/rabbitmg-backend-server:v2"
    env_file:
      - .env-non-dev
    container_name: "fastapi_app"
    command: ["/fastapi_app/app.sh"]
    ports:
      - "9000:8000"
    depends_on:
      - db_dev
    networks:
      - custom2

networks:
  custom2:
    driver: bridge




