version: "3.0"
services:
  db:
    container_name: "rabbit_mg_Postgres"
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - .env-non-dev
    ports:
      - "5555:5432"
    networks:
      - custom

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: "fastapi_app"
    command: ["/fastapi_app/app.sh"]
    ports:
      - "9000:8000"
    depends_on:
      - db
    networks:
      - custom


networks:
  custom:
    driver: bridge




