"""adding pidoras

Revision ID: c8f24bc08b8e
Revises: d7db53b0f238
Create Date: 2023-11-01 14:35:50.425044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f24bc08b8e'
down_revision: Union[str, None] = 'd7db53b0f238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pidor', sa.Boolean()))
    op.execute("UPDATE users SET is_pidor = False WHERE is_pidor IS NULL")
    op.alter_column('users', 'is_pidor', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_pidor')
    # ### end Alembic commands ###
