"""add SportClass

Revision ID: a3c5ce8bf38b
Revises: c2be6c48d5d8
Create Date: 2023-11-20 13:06:02.951655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c5ce8bf38b'
down_revision: Union[str, None] = 'c2be6c48d5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_class', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_class')
    )
    op.create_table('ggp_subclasses_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sport_classes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_classes_id'], ['sport_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sport_classes_id', name='idx_unique_user_class')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ggp_subclasses_lists')
    op.drop_table('sport_classes')
    # ### end Alembic commands ###
