"""bugfix

Revision ID: faa33b734f9f
Revises: d7db53b0f238
Create Date: 2023-11-02 08:39:58.678743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa33b734f9f'
down_revision: Union[str, None] = 'd7db53b0f238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sub_ggp_percent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False, postgresql_using='sub_ggp_percent::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sub_ggp_percent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
