"""Init first base

Revision ID: 6ed6166726a2
Revises: 
Create Date: 2023-10-28 15:56:29.647497

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6ed6166726a2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("ggp_percent_begin", sa.Integer(), nullable=False),
        sa.Column("ggp_percent_end", sa.Integer(), nullable=False),
        sa.Column("sub_ggp_percent", sa.Integer(), nullable=False),
        sa.Column("sub_offline", sa.Boolean(), nullable=False),
        sa.Column("sub_ggp", sa.Boolean(), nullable=False),
        sa.Column("sub_world_record", sa.Boolean(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("login", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
