on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Set PR number as an environment variable
      run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
    - name: Set Branch name as an environment variable
      run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
    - name: connect and pull
      run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.TEST_DIR }} &&
          git checkout -b temp-pr-${{ github.event.pull_request.number }} &&
          git fetch origin pull/${{ github.event.pull_request.number }}/head &&
          git checkout temp-pr-${{ github.event.pull_request.number }} &&
          git merge FETCH_HEAD &&
          PR_NUMBER=${PR_NUMBER}
          BRANCH_NAME=${BRANCH_NAME}
          ./rebuild_server.sh &&
          exit"
    - name: cleanup
      run: rm -rf ~/.ssh
